### PR TITLE
Preserve mtime of copied files

### LINKED ISSUE #58: File timestamp set to Jan 1, 1970
The timestamps of the files copied into the docker images is always Jan 1, 1970

### PR DESCRIPTION
**Pull request by davidxia**
Fixes #58

### CODE REVIEW

**Comment by davidxia** [comment]
@rohansingh

**Comment by rohansingh** [comment]
Ha. Brilliant. It actually preserves the mtime though? Any way to test that?

**Comment by davidxia** [comment]
I can test it now and just docker exec stat <file>

**Comment by davidxia** [comment]
@rohansingh But why did @dflemstr say [here](https://github.com/spotify/docker-maven-plugin/pull/49#issue-52745564):

> Preserving the source mtime doesn't work because Git changes mtime all the time, which is annoying too.

Not sure I understand what he means.

**Comment by rohansingh** [comment]
Yeah when you clone a repo the mtime of all files is set to clone time. But that seems orthogonal to me. If your source control does stuff with mtime's, fine, whatever, but we should do our best to ensure that the file in the Docker image ends up having the same mtime as the source file on disk. That's how `COPY` in a Dockerfile works after all.

**Comment by davidxia** [comment]
Seems to work:

Inside container:

```
root@cac969027ae1:/# stat helioscanary-0.7.0.jar
  File: 'helioscanary-0.7.0.jar'
  Size: 32122581  	Blocks: 62744      IO Block: 4096   regular file
Device: 1dh/29d	Inode: 67          Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2015-06-10 18:03:56.331636554 +0000
Modify: 2015-06-10 18:04:21.000000000 +0000
Change: 2015-06-10 18:03:56.371638772 +0000
 Birth: -
```

outside container

```
ls -ail target/helioscanary-0.7.0.jar
11849177 -rw-r--r--  1 dxia  staff  32122581 Jun 10 14:04 target/helioscanary-0.7.0.jar
```

**Comment by rohansingh** [comment]
Great.

**Comment by sjardine** [comment]
Fixed for me.

**Pull request merged**
