### PR TITLE
DockerBuildInformation - reads Git repo and commit

### PR DESCRIPTION
**Pull request by evgeny-goldin**

### CODE REVIEW

**Comment by evgeny-goldin** [comment]
This PR stores two additional fields in `"target/test-classes/image_info.json"` when image is built: `"commit"` and `"repo"`. For example:

    $ cat target/test-classes/image_info.json
    {"commit":"588dc4e341aba758067362b7795587a1872517eb","image":"registry/my-service:0.0.1-SNAPSHOT-588dc4e.DIRTY","repo":"git@repo:user/my-service.git"}

**Comment by davidxia** [comment]
I was trying to add a test like this https://github.com/spotify/docker-maven-plugin/tree/dxia/add-test-for-git-data. But couldn't figure out how to do it using a test fixture for the `.git` dir.

**Comment by rculbertson** [comment]
:+1:

**Comment by evgeny-goldin** [comment]
That was fast. Thanks, Ryan!

**Pull request merged**
