### PR TITLE
ensure entire directories are copied for ADDs

### LINKED ISSUE #146: Resource directories are not copied
Since version 0.3.0 it is not possible to copy whole resource directories to the build directory.

This doesn't work any more:
```xml
<resource>
    <targetPath>/data</targetPath>
    <directory>${project.basedir}/data<directory>
</resource>
```

The problem was introduced with 62eaa8a8fda7200fd041387400894d908a9f975c

https://github.com/spotify/docker-maven-plugin/blob/master/src/main/java/com/spotify/docker/BuildMojo.java#L640
```java
if (copyWholeDir) {
        copiedPaths.add(separatorsToUnix(targetPath));
 } else {
        for (String included : includedFiles) {
          final Path sourcePath = Paths.get(resource.getDirectory(), included);
          final Path destPath = Paths.get(destination, targetPath, included);
          getLog().info(String.format("Copying %s -> %s", sourcePath, destPath));
          // ensure all directories exist because copy operation will fail if they don't
          Files.createDirectories(destPath.getParent());
          Files.copy(sourcePath, destPath, StandardCopyOption.REPLACE_EXISTING,
                     StandardCopyOption.COPY_ATTRIBUTES);

          copiedPaths.add(separatorsToUnix(Paths.get(targetPath, included).toString()));
     }
}
```

If `copyWholeDir` was set, the logic for copy Files will be skipped.

### PR DESCRIPTION
**Pull request by mattnworb**
Prior to this change, a mojo configuration like

```
<resource>
  <directory>some/directory</directory>
  <targetPath>/data</targetPath>
</resource>
```

would generate an `ADD /data /data` instruction but the `some/directory`
directory is never copied into the Docker build context directory, so
the actual build will fail.

With this change, the directory is copied to the build context
directory.

Note: it might seem weird that the `targetPath` is used as the directory
name to use *inside* the build context as opposed to just the target
path inside the container, but this is to mirror behavior when copying
individual files.

Fixes #146.

### CODE REVIEW

**Comment by mattnworb** [comment]
@davidxia @gimaker @rohansingh @dawidmalina

**Comment by davidxia** [comment]
awesome :+1:

**Comment by dawidmalina** [comment]
:+1:

**Comment by Derek-Ashmore** [comment]
FYI -- I'm using 0.4.0, which should have this fix in it as I understand it.  This is still an issue.  No matter what I do, can't get my application jar into the docker image.

**Comment by mattnworb** [comment]
@Derek-Ashmore what does your Dockerfile look like?

**Comment by Derek-Ashmore** [comment]
Thanks for the quick response -- the last line of this is just me trying to find the jar that's supposed to be there.

[dockerfile.txt](https://github.com/spotify/docker-maven-plugin/files/111623/dockerfile.txt)

**Comment by mattnworb** [comment]
@Derek-Ashmore is your build actually putting the jar in `target/app`? Keep in mind that this plugin uses the `<directory>` inside the `<resource>` as [the directory in which to find the file](https://github.com/spotify/docker-maven-plugin/blob/master/src/main/java/com/spotify/docker/BuildMojo.java#L689).

If you run your build with `-X` the plugin will spit out a bunch of information about where it is copying files which I think would help you out.

btw, you may find it is much easier to use Maven properties such as `${project.basedir}` or `${project.build.directory}` so that your build is portable rather than using absolute file paths.

**Comment by Derek-Ashmore** [comment]
Yes, the build is putting the jar in target/app.  According to the debug messages, it is getting moved to docker/app during the build process.  Thx for looking at this.


Thanks,Derek    


-------- Original message --------

**Comment by Derek-Ashmore** [comment]
Hi -- I have more information.  The jar file *is* in the temporary gz file that gets transmitted to the docker machine.  A link to the gz file transmitted is available here:  https://drive.google.com/file/d/0BywOAPVO4FvAcHZEUVRKUHFuVkU/view?usp=sharing

Also, I put a short test together with the Docker Client directly -- I get the same behavior.  The gz (with the jar) goes up, the docker file executes with the same debug output as if I go through the maven plugin, and the jar is *not* in the resulting container.   

Test Docker client code:

@Test
	public void test() throws Exception {
		final DockerClient docker = DefaultDockerClient.fromEnv().build();
		//docker.pull("busybox");
		docker.build(Paths.get("src/test/docker"), "moneta-springboot-0.9.2-alpha", new BuildParam[0]);
	}

**Comment by chris-snider** [comment]
Hi,

I see in the Dockerfile that you are using the ENTRYPOINT, but I don’t see where you are actually adding the jar to the image.  You need a COPY or ADD command e.g.
ADD /app/moneta-springboot.jar /app/



Chris Snider
Senior Software Engineer
Intelligent Software Solutions, Inc.
[Description: Description: Description: cid:image001.png@01CA1F1F.CBC93990]

**Comment by mattnworb** [comment]
thanks @chris-snider , that would definitely be the cause of the problem then for @Derek-Ashmore .

**Comment by Derek-Ashmore** [comment]
OK -- I'm officially embarrassed.  Thanks for the assistance - sorry for the red herring.

**Comment by chris-snider** [comment]
It is the individual trees we sometimes miss when looking at an entire forest :D

Chris Snider
Senior Software Engineer
Intelligent Software Solutions, Inc.
[Description: Description: Description: cid:image001.png@01CA1F1F.CBC93990]

**Pull request merged**
