### PR TITLE
Upgrade docker-client dep from 3.3.4 to 3.5.1

### PR DESCRIPTION
**Pull request by davidxia**

### CODE REVIEW

**Comment by davidxia** [comment]
Fixes #143

**Comment by mattnworb** [comment]
@davidxia seems like `docker:client:3.5.1` is [not in maven central](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.spotify%22%20AND%20a%3A%22docker-client%22)?

**Comment by davidxia** [comment]
Yea I'm waiting for it to be indexed.

On Friday, January 15, 2016, Matt Brown <notifications@github.com> wrote:

> @davidxia <https://github.com/davidxia> seems like docker:client:3.5.1 is not
> in maven central
> <https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.spotify%22%20AND%20a%3A%22docker-client%22>?
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/docker-maven-plugin/pull/178#issuecomment-172092617>
> .
>


-- 
David Xia
Software Engineer
dxia@spotify.com

**Comment by davidxia** [comment]
@mattnworb @rohansingh

**Comment by mattnworb** [comment]
:+1:

**Pull request merged**
