### PR TITLE
update to docker-client:4.0.8

### PR DESCRIPTION
**Pull request by mattnworb**
Contains a change to default to the DOCKER_HOST that Docker for Mac uses
when run on OS X.

### CODE REVIEW

**Comment by mattnworb** [comment]
@davidxia

**Comment by davidxia** [comment]
👍

**Comment by mattnworb** [comment]
yep https://github.com/spotify/docker-client/commit/c2975a44ee8ec28bc5b1fa5917f5de4a54cd93ef

**Comment by davidxia** [comment]
should we wait until I get this done? https://github.com/spotify/docker-client/pull/441

**Comment by mattnworb** [comment]
doesn't seem necessary to me as that PR is just an internal refactoring

**Pull request merged**
