### PR TITLE
don't set empty CMD when not configured

### LINKED ISSUE #118: Empty CMD output
if I do not specify a command, the resulting docker file looks like this. I would expect it to not include the CMD if i do not specify one. I want to just inherit the parent image's CMD, which is how it works if you omit the statement. What do you suggest?

````
FROM btf/jetty
CMD []
ADD /var/lib/jetty/webapps/api.war /var/lib/jetty/webapps/api.war
````

### PR DESCRIPTION
**Pull request by mattnworb**
Fixes #118.

### CODE REVIEW

**Comment by mattnworb** [comment]
@davidxia

**Comment by davidxia** [comment]
:+1: I wonder what the initial reason for this was...

**Comment by mattnworb** [comment]
Maybe @danielnorberg or @rculbertson knows?

**Comment by rculbertson** [comment]
@mattnworb It may have been a workaround for weird behavior in early versions of docker. I want to say if we didn't set CMD explicitly it got set to something invalid. Should be safe to merge if that is no longer the case.

**Comment by mattnworb** [comment]
Thanks, as far as I can tell it's not an issue anymore (tested with 1.6.0 and 1.9.0).

**Comment by mattnworb** [comment]
I also tested this building an image where the source image has a CMD itself, and looks like the child image having no CMD inherits the other one as expected

```
$ cat Dockerfile
FROM tomcat:8.0.20-jre8
RUN date
ENV FOO bar

$ docker build .
Sending build context to Docker daemon 2.048 kB
...
Successfully built 47ee30b6dd4a

$ docker run -it 47ee3
Using CATALINA_BASE:   /usr/local/tomcat
Using CATALINA_HOME:   /usr/local/tomcat
Using CATALINA_TMPDIR: /usr/local/tomcat/temp
Using JRE_HOME:        /usr
Using CLASSPATH:       /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar
06-Nov-2015 20:21:20.187 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.0.20
06-Nov-2015 20:21:20.191 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Feb 15 2015 18:10:42 UTC
...
```

(thanks to @nbleisch for mentioning the tomcat image in his issue in #118)

**Pull request merged**
