### PR TITLE
Added new Feature so that volumes can be specified in POM

### PR DESCRIPTION
**Pull request by officialpatterson**
Modified two files to allow the specifying of volumes in the POM configuration.

### CODE REVIEW

**Comment by mattnworb** [comment]
Thanks @officialpatterson for the contribution! The test fails though, looks like you forgot to add `src/test/resources/pom-build-docker-volumes.xml` in the commit?

**Comment by dawidmalina** [comment]
:+1:

**Comment by dawidmalina** [comment]
@mattnworb when this can be merged and released?

**Comment by mattnworb** [comment]
Would the syntax for specifying multiple arguments (to use an alternate name inside the container) be simply `/path1 /path2`? I think it would be good to add some examples to the parameter's javadoc.

Otherwise LGTM :+1:

**Comment by dawidmalina** [comment]
Any progress on this?

**Comment by mattnworb** [comment]
I was hoping for some clarification/documentation to the question above but I think it's ok to merge as is.

**Pull request merged**
